// <auto-generated />
namespace mvcproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class c3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261802085_c3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
